text = input("Enter a sentence: ")
words = text.split()
char_no_spaces = len(text.replace(" ", ""))
print(f"\nOriginal: {text}")
print(f"Characters (with spaces): {len(text)}")
print(f"Characters (without spaces): {char_no_spaces}")
print(f"Words: {len(words)}")
print(f"UPPERCASE: {text.upper()}")
print(f"lowercase: {text.lower()}")
print(f"Title Case: {text.title()}")
print(f"First word: {words[0] if words else ''}")
print(f"Last word: {words[-1] if words else ''}")
print(f"Reversed: {text[::-1]}")